// Autogenerated Jamon implementation
// /root/apps/test/jamon-dist-2013.12.28/./jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon

package org.apache.hadoop.hbase.tmpl.master;

// 32, 1
import java.util.*;
// 33, 1
import java.io.IOException;
// 34, 1
import org.apache.hadoop.hbase.client.replication.ReplicationPeerConfigUtil;
// 35, 1
import org.apache.hadoop.hbase.client.RegionInfo;
// 36, 1
import org.apache.hadoop.hbase.client.TableDescriptor;
// 37, 1
import org.apache.hadoop.hbase.replication.ReplicationPeerConfig;
// 38, 1
import org.apache.hadoop.hbase.replication.ReplicationPeerDescription;
// 39, 1
import org.apache.hadoop.hbase.HBaseConfiguration;
// 40, 1
import org.apache.hadoop.hbase.HConstants;
// 41, 1
import org.apache.hadoop.hbase.HTableDescriptor;
// 42, 1
import org.apache.hadoop.hbase.NamespaceDescriptor;
// 43, 1
import org.apache.hadoop.hbase.ServerName;
// 44, 1
import org.apache.hadoop.hbase.TableName;
// 45, 1
import org.apache.hadoop.hbase.client.Admin;
// 46, 1
import org.apache.hadoop.hbase.client.MasterSwitchType;
// 47, 1
import org.apache.hadoop.hbase.client.TableState;
// 48, 1
import org.apache.hadoop.hbase.master.assignment.AssignmentManager;
// 49, 1
import org.apache.hadoop.hbase.master.DeadServer;
// 50, 1
import org.apache.hadoop.hbase.master.HMaster;
// 51, 1
import org.apache.hadoop.hbase.master.RegionState;
// 52, 1
import org.apache.hadoop.hbase.master.ServerManager;
// 53, 1
import org.apache.hadoop.hbase.protobuf.ProtobufUtil;
// 54, 1
import org.apache.hadoop.hbase.quotas.QuotaUtil;
// 55, 1
import org.apache.hadoop.hbase.security.access.AccessControlLists;
// 56, 1
import org.apache.hadoop.hbase.security.visibility.VisibilityConstants;
// 57, 1
import org.apache.hadoop.hbase.shaded.protobuf.generated.SnapshotProtos.SnapshotDescription;
// 58, 1
import org.apache.hadoop.hbase.tool.CanaryTool;
// 59, 1
import org.apache.hadoop.hbase.util.Bytes;
// 60, 1
import org.apache.hadoop.hbase.util.FSUtils;
// 61, 1
import org.apache.hadoop.hbase.util.JvmVersion;
// 62, 1
import org.apache.hadoop.util.StringUtils;

public class MasterStatusTmplImpl
  extends org.jamon.AbstractTemplateImpl
  implements org.apache.hadoop.hbase.tmpl.master.MasterStatusTmpl.Intf

{
  private final HMaster master;
  private final AssignmentManager assignmentManager;
  private final boolean catalogJanitorEnabled;
  private final Set<ServerName> deadServers;
  private final String filter;
  private final String format;
  private final Map<String,Integer> frags;
  private final ServerName metaLocation;
  private final ServerManager serverManager;
  private final List<ServerName> servers;
  // 74, 1
  
  public String formatZKString() {
    StringBuilder quorums = new StringBuilder();
    String zkQuorum = master.getZooKeeper().getQuorum();

    if (null == zkQuorum) {
      return quorums.toString();
    }

    String[] zks = zkQuorum.split(",");

    if (zks.length == 0) {
      return quorums.toString();
    }

    for(int i = 0; i < zks.length; ++i) {
      quorums.append(zks[i].trim());

      if (i != (zks.length - 1)) {
        quorums.append("<br/>");
      }
    }

    return quorums.toString();
  }

  // 101, 1
  
  public static String getUserTables(HMaster master, List<TableDescriptor> tables){
    if (master.isInitialized()){
      try {
        Map<String, TableDescriptor> descriptorMap = master.getTableDescriptors().getAll();
        if (descriptorMap != null) {
          for (TableDescriptor desc : descriptorMap.values()) {
            if (!desc.getTableName().isSystemTable()) {
             tables.add(desc);
            }
          }
        }
      } catch (IOException e) {
        return "Got user tables error, " + e.getMessage();
      }
    }
    return null;
  }

  protected static org.apache.hadoop.hbase.tmpl.master.MasterStatusTmpl.ImplData __jamon_setOptionalArguments(org.apache.hadoop.hbase.tmpl.master.MasterStatusTmpl.ImplData p_implData)
  {
    if(! p_implData.getAssignmentManager__IsNotDefault())
    {
      p_implData.setAssignmentManager(null);
    }
    if(! p_implData.getCatalogJanitorEnabled__IsNotDefault())
    {
      p_implData.setCatalogJanitorEnabled(true);
    }
    if(! p_implData.getDeadServers__IsNotDefault())
    {
      p_implData.setDeadServers(null);
    }
    if(! p_implData.getFilter__IsNotDefault())
    {
      p_implData.setFilter("general");
    }
    if(! p_implData.getFormat__IsNotDefault())
    {
      p_implData.setFormat("html");
    }
    if(! p_implData.getFrags__IsNotDefault())
    {
      p_implData.setFrags(null);
    }
    if(! p_implData.getMetaLocation__IsNotDefault())
    {
      p_implData.setMetaLocation(null);
    }
    if(! p_implData.getServerManager__IsNotDefault())
    {
      p_implData.setServerManager(null);
    }
    if(! p_implData.getServers__IsNotDefault())
    {
      p_implData.setServers(null);
    }
    return p_implData;
  }
  public MasterStatusTmplImpl(org.jamon.TemplateManager p_templateManager, org.apache.hadoop.hbase.tmpl.master.MasterStatusTmpl.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    master = p_implData.getMaster();
    assignmentManager = p_implData.getAssignmentManager();
    catalogJanitorEnabled = p_implData.getCatalogJanitorEnabled();
    deadServers = p_implData.getDeadServers();
    filter = p_implData.getFilter();
    format = p_implData.getFormat();
    frags = p_implData.getFrags();
    metaLocation = p_implData.getMetaLocation();
    serverManager = p_implData.getServerManager();
    servers = p_implData.getServers();
  }
  
  @Override public void renderNoFlush(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 65, 1
    if (format.equals("json") )
    {
      // 65, 30
      jamonWriter.write("\r\n  ");
      // 66, 3
      {
        org.apache.hadoop.hbase.tmpl.common.TaskMonitorTmpl __jamon__var_0 = new org.apache.hadoop.hbase.tmpl.common.TaskMonitorTmpl(this.getTemplateManager());
        __jamon__var_0.setFilter(filter);
        __jamon__var_0.setFormat("json" );
        __jamon__var_0.renderNoFlush(jamonWriter);
      }
      // 66, 68
      jamonWriter.write("\r\n  ");
      // 67, 3
      return; 
    }
    // 68, 7
    jamonWriter.write("\r\n");
    // 69, 1
    
ServerManager serverManager = master.getServerManager();
AssignmentManager assignmentManager = master.getAssignmentManager();

    // 121, 1
    jamonWriter.write("<!DOCTYPE html>\r\n<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<html lang=\"en\">\r\n  <head>\r\n    <meta charset=\"utf-8\">\r\n    <title>");
    // 126, 12
    if (master.isActiveMaster() )
    {
      // 126, 43
      jamonWriter.write("Master: ");
    }
    // 126, 51
    else
    {
      // 126, 58
      jamonWriter.write("Backup Master: ");
    }
    // 126, 79
    jamonWriter.write("\r\n    ");
    // 127, 5
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(master.getServerName().getHostname()), jamonWriter);
    // 127, 47
    jamonWriter.write("</title>\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <meta name=\"description\" content=\"\">\r\n    <link href=\"/static/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n    <link href=\"/static/css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n    <link href=\"/static/css/hbase.css\" rel=\"stylesheet\">\r\n  </head>\r\n\r\n  <body>\r\n\r\n    <div class=\"navbar  navbar-fixed-top navbar-default\">\r\n        <div class=\"container-fluid\">\r\n            <div class=\"navbar-header\">\r\n                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n                    <span class=\"icon-bar\"></span>\r\n                    <span class=\"icon-bar\"></span>\r\n                    <span class=\"icon-bar\"></span>\r\n                </button>\r\n                <a class=\"navbar-brand\" href=\"/master-status\"><img src=\"/static/hbase_logo_small.png\" alt=\"HBase Logo\"/></a>\r\n            </div>\r\n            <div class=\"collapse navbar-collapse\">\r\n                <ul class=\"nav navbar-nav\">\r\n                <li class=\"active\"><a href=\"/master-status\">Home</a></li>\r\n                <li><a href=\"/tablesDetailed.jsp\">Table Details</a></li>\r\n                ");
    // 151, 17
    if (master.isActiveMaster() )
    {
      // 151, 48
      jamonWriter.write("\r\n                    <li><a href=\"/procedures.jsp\">Procedures &amp; Locks</a></li>\r\n                    <li><a href=\"/hbck.jsp\">HBCK Report</a></li>\r\n                    ");
      // 154, 21
      if (master.getConfiguration().getBoolean(QuotaUtil.QUOTA_CONF_KEY, false) )
      {
        // 154, 98
        jamonWriter.write("\r\n                        <li><a href=\"/quotas.jsp\">Quotas</a></li>\r\n                    ");
      }
      // 156, 27
      jamonWriter.write("\r\n                ");
    }
    // 157, 23
    jamonWriter.write("\r\n                <li><a href=\"/processMaster.jsp\">Process Metrics</a></li>\r\n                <li><a href=\"/logs/\">Local Logs</a></li>\r\n                <li><a href=\"/logLevel\">Log Level</a></li>\r\n                <li><a href=\"/dump\">Debug Dump</a></li>\r\n                <li><a href=\"/jmx\">Metrics Dump</a></li>\r\n                <li><a href=\"/prof\">Profiler</a></li>\r\n                ");
    // 164, 17
    if (HBaseConfiguration.isShowConfInServlet())
    {
      // 164, 64
      jamonWriter.write("\r\n                <li><a href=\"/conf\">HBase Configuration</a></li>\r\n                ");
    }
    // 166, 23
    jamonWriter.write("\r\n               </ul>\r\n            </div><!--/.nav-collapse -->\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"container-fluid content\">\r\n\t");
    // 173, 2
    if (master.isActiveMaster() )
    {
      // 173, 33
      jamonWriter.write("\r\n        <div class=\"row inner_header\">\r\n            <div class=\"page-header\">\r\n                <h1>Master <small>");
      // 176, 35
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(master.getServerName().getHostname()), jamonWriter);
      // 176, 77
      jamonWriter.write("</small></h1>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"row\">\r\n        <!-- Various warnings that cluster admins should be aware of -->\r\n        ");
      // 182, 9
      if (JvmVersion.isBadJvmVersion() )
      {
        // 182, 45
        jamonWriter.write("\r\n          <div class=\"alert alert-error\">\r\n          Your current JVM version ");
        // 184, 36
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(System.getProperty("java.version")), jamonWriter);
        // 184, 76
        jamonWriter.write(" is known to be\r\n          unstable with HBase. Please see the\r\n          <a href=\"http://hbase.apache.org/book.html#trouble.log.gc\">HBase Reference Guide</a>\r\n          for details.\r\n          </div>\r\n        ");
      }
      // 189, 15
      jamonWriter.write("\r\n        ");
      // 190, 9
      if (master.isInitialized() && !catalogJanitorEnabled )
      {
        // 190, 65
        jamonWriter.write("\r\n          <div class=\"alert alert-error\">\r\n          Please note that your cluster is running with the CatalogJanitor disabled. It can be\r\n          re-enabled from the hbase shell by running the command 'catalogjanitor_switch true'\r\n          </div>\r\n        ");
      }
      // 195, 15
      jamonWriter.write("\r\n        ");
      // 196, 9
      if (master.isInMaintenanceMode() )
      {
        // 196, 45
        jamonWriter.write("\r\n          <div class=\"alert alert-warning\">\r\n          Your Master is in maintenance mode. This is because hbase.master.maintenance_mode is\r\n          set to true. Under the maintenance mode, no quota or no Master coprocessor is loaded.\r\n          </div>\r\n        ");
      }
      // 201, 15
      jamonWriter.write("\r\n        ");
      // 202, 9
      if (!master.isBalancerOn() )
      {
        // 202, 39
        jamonWriter.write("\r\n          <div class=\"alert alert-warning\">\r\n            The Load Balancer is not enabled which will eventually cause performance degradation\r\n            in HBase as Regions will not be distributed across all RegionServers. The balancer\r\n            is only expected to be disabled during rolling upgrade scenarios.\r\n          </div>\r\n        ");
      }
      // 208, 15
      jamonWriter.write("\r\n        ");
      // 209, 9
      if (!master.isSplitOrMergeEnabled(MasterSwitchType.SPLIT) )
      {
        // 209, 70
        jamonWriter.write("\r\n          <div class=\"alert alert-warning\">\r\n            Region splits are disabled. This may be the result of HBCK aborting while\r\n            running in repair mode. Manually enable splits from the HBase shell,\r\n            or re-run HBCK in repair mode.\r\n          </div>\r\n        ");
      }
      // 215, 15
      jamonWriter.write("\r\n        ");
      // 216, 9
      if (!master.isSplitOrMergeEnabled(MasterSwitchType.MERGE) )
      {
        // 216, 70
        jamonWriter.write("\r\n          <div class=\"alert alert-warning\">\r\n            Region merges are disabled. This may be the result of HBCK aborting while\r\n            running in repair mode. Manually enable merges from the HBase shell,\r\n            or re-run HBCK in repair mode.\r\n          </div>\r\n        ");
      }
      // 222, 15
      jamonWriter.write("\r\n        ");
      // 223, 9
      if (master.getAssignmentManager() != null )
      {
        // 223, 54
        jamonWriter.write("\r\n          ");
        // 224, 11
        {
          org.apache.hadoop.hbase.tmpl.master.AssignmentManagerStatusTmpl __jamon__var_1 = new org.apache.hadoop.hbase.tmpl.master.AssignmentManagerStatusTmpl(this.getTemplateManager());
          __jamon__var_1.renderNoFlush(jamonWriter, master.getAssignmentManager());
        }
        // 224, 92
        jamonWriter.write("\r\n        ");
      }
      // 225, 15
      jamonWriter.write("\r\n        ");
      // 226, 9
      if (!master.isInMaintenanceMode() )
      {
        // 226, 46
        jamonWriter.write("\r\n          ");
        // 227, 11
        if (master.getMasterCoprocessorHost().findCoprocessor("RSGroupAdminEndpoint") != null )
        {
          // 227, 100
          jamonWriter.write("\r\n            <section>\r\n              <h2><a name=\"rsgroup\">RSGroup</a></h2>\r\n              ");
          // 230, 15
          {
            org.apache.hadoop.hbase.tmpl.master.RSGroupListTmpl __jamon__var_2 = new org.apache.hadoop.hbase.tmpl.master.RSGroupListTmpl(this.getTemplateManager());
            __jamon__var_2.renderNoFlush(jamonWriter, master, serverManager);
          }
          // 230, 81
          jamonWriter.write("\r\n            </section>\r\n          ");
        }
        // 232, 17
        jamonWriter.write("\r\n        ");
      }
      // 233, 15
      jamonWriter.write("\r\n        <section>\r\n            <h2><a name=\"regionservers\">Region Servers</a></h2>\r\n            ");
      // 236, 13
      {
        org.apache.hadoop.hbase.tmpl.master.RegionServerListTmpl __jamon__var_3 = new org.apache.hadoop.hbase.tmpl.master.RegionServerListTmpl(this.getTemplateManager());
        __jamon__var_3.setServers(servers );
        __jamon__var_3.renderNoFlush(jamonWriter, master);
      }
      // 236, 74
      jamonWriter.write("\r\n\r\n            ");
      // 238, 13
      if ((deadServers != null) )
      {
        // 238, 42
        jamonWriter.write("\r\n                ");
        // 239, 17
        {
          // 239, 17
          __jamon_innerUnit__deadRegionServers(jamonWriter);
        }
        // 239, 40
        jamonWriter.write("\r\n            ");
      }
      // 240, 19
      jamonWriter.write("\r\n        </section>\r\n        <section>\r\n            ");
      // 243, 13
      {
        org.apache.hadoop.hbase.tmpl.master.BackupMasterStatusTmpl __jamon__var_4 = new org.apache.hadoop.hbase.tmpl.master.BackupMasterStatusTmpl(this.getTemplateManager());
        __jamon__var_4.renderNoFlush(jamonWriter, master );
      }
      // 243, 58
      jamonWriter.write("\r\n        </section>\r\n        <section>\r\n            <h2><a name=\"tables\">Tables</a></h2>\r\n            <div class=\"tabbable\">\r\n                <ul class=\"nav nav-pills\">\r\n                    <li class=\"active\">\r\n                        <a href=\"#tab_userTables\" data-toggle=\"tab\">User Tables</a>\r\n                    </li>\r\n                    <li class=\"\">\r\n                        <a href=\"#tab_catalogTables\" data-toggle=\"tab\">System Tables</a>\r\n                    </li>\r\n                    <li class=\"\">\r\n                        <a href=\"#tab_userSnapshots\" data-toggle=\"tab\">Snapshots</a>\r\n                    </li>\r\n                </ul>\r\n                <div class=\"tab-content\" style=\"padding-bottom: 9px; border-bottom: 1px solid #ddd;\">\r\n                    <div class=\"tab-pane active\" id=\"tab_userTables\">\r\n                        ");
      // 261, 25
      if ((metaLocation != null) )
      {
        // 261, 55
        jamonWriter.write("\r\n                            ");
        // 262, 29
        {
          // 262, 29
          __jamon_innerUnit__userTables(jamonWriter);
        }
        // 262, 45
        jamonWriter.write("\r\n                        ");
      }
      // 263, 31
      jamonWriter.write("\r\n                    </div>\r\n                    <div class=\"tab-pane\" id=\"tab_catalogTables\">\r\n                        ");
      // 266, 25
      if ((metaLocation != null) )
      {
        // 266, 55
        jamonWriter.write("\r\n                            ");
        // 267, 29
        {
          // 267, 29
          __jamon_innerUnit__catalogTables(jamonWriter);
        }
        // 267, 48
        jamonWriter.write("\r\n                        ");
      }
      // 268, 31
      jamonWriter.write("\r\n                    </div>\r\n                    <div class=\"tab-pane\" id=\"tab_userSnapshots\">\r\n                        ");
      // 271, 25
      {
        // 271, 25
        __jamon_innerUnit__userSnapshots(jamonWriter);
      }
      // 271, 44
      jamonWriter.write("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </section>\r\n        <section>\r\n            <h2><a name=\"peers\">Peers</a></h2>\r\n            ");
      // 278, 13
      {
        // 278, 13
        __jamon_innerUnit__peerConfigs(jamonWriter);
      }
      // 278, 30
      jamonWriter.write("\r\n        </section>\r\n\t");
    }
    // 280, 2
    else
    {
      // 280, 9
      jamonWriter.write("\r\n        <section>\r\n            ");
      // 282, 13
      {
        org.apache.hadoop.hbase.tmpl.master.BackupMasterStatusTmpl __jamon__var_5 = new org.apache.hadoop.hbase.tmpl.master.BackupMasterStatusTmpl(this.getTemplateManager());
        __jamon__var_5.renderNoFlush(jamonWriter, master );
      }
      // 282, 58
      jamonWriter.write("\r\n        </section>\r\n\t");
    }
    // 284, 8
    jamonWriter.write("\r\n\r\n\r\n        <section>\r\n            ");
    // 288, 13
    {
      org.apache.hadoop.hbase.tmpl.common.TaskMonitorTmpl __jamon__var_6 = new org.apache.hadoop.hbase.tmpl.common.TaskMonitorTmpl(this.getTemplateManager());
      __jamon__var_6.setFilter(filter);
      __jamon__var_6.setParent("/master-status" );
      __jamon__var_6.renderNoFlush(jamonWriter);
    }
    // 288, 88
    jamonWriter.write("\r\n        </section>\r\n\r\n        <section>\r\n            <h2><a name=\"attributes\">Software Attributes</a></h2>\r\n            <table id=\"attributes_table\" class=\"table table-striped\">\r\n                <tr>\r\n                    <th>Attribute Name</th>\r\n                    <th>Value</th>\r\n                    <th>Description</th>\r\n                </tr>\r\n                <tr>\r\n                    <td>HBase Version</td>\r\n                    <td>");
    // 301, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.hbase.util.VersionInfo.getVersion()), jamonWriter);
    // 301, 84
    jamonWriter.write(", revision=");
    // 301, 95
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.hbase.util.VersionInfo.getRevision()), jamonWriter);
    // 301, 155
    jamonWriter.write("</td><td>HBase version and revision</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>HBase Compiled</td>\r\n                    <td>");
    // 305, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.hbase.util.VersionInfo.getDate()), jamonWriter);
    // 305, 81
    jamonWriter.write(", ");
    // 305, 83
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.hbase.util.VersionInfo.getUser()), jamonWriter);
    // 305, 139
    jamonWriter.write("</td>\r\n                    <td>When HBase version was compiled and by whom</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>HBase Source Checksum</td>\r\n                    <td>");
    // 310, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.hbase.util.VersionInfo.getSrcChecksum()), jamonWriter);
    // 310, 88
    jamonWriter.write("</td>\r\n                    <td>HBase source MD5 checksum</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>Hadoop Version</td>\r\n                    <td>");
    // 315, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.util.VersionInfo.getVersion()), jamonWriter);
    // 315, 78
    jamonWriter.write(", revision=");
    // 315, 89
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.util.VersionInfo.getRevision()), jamonWriter);
    // 315, 143
    jamonWriter.write("</td>\r\n                    <td>Hadoop version and revision</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>Hadoop Compiled</td>\r\n                    <td>");
    // 320, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.util.VersionInfo.getDate()), jamonWriter);
    // 320, 75
    jamonWriter.write(", ");
    // 320, 77
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.util.VersionInfo.getUser()), jamonWriter);
    // 320, 127
    jamonWriter.write("</td>\r\n                    <td>When Hadoop version was compiled and by whom</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>Hadoop Source Checksum</td>\r\n                    <td>");
    // 325, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.hadoop.util.VersionInfo.getSrcChecksum()), jamonWriter);
    // 325, 82
    jamonWriter.write("</td>\r\n                    <td>Hadoop source MD5 checksum</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>ZooKeeper Client Version</td>\r\n                    <td>");
    // 330, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.zookeeper.Version.getVersion()), jamonWriter);
    // 330, 72
    jamonWriter.write(", revision=");
    // 330, 83
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.zookeeper.Version.getRevision()), jamonWriter);
    // 330, 131
    jamonWriter.write("</td>\r\n                    <td>ZooKeeper client version and revision</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>ZooKeeper Client Compiled</td>\r\n                    <td>");
    // 335, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(org.apache.zookeeper.Version.getBuildDate()), jamonWriter);
    // 335, 74
    jamonWriter.write("</td>\r\n                    <td>When ZooKeeper client version was compiled</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>ZooKeeper Quorum</td>\r\n                    <td> ");
    // 341, 26
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(formatZKString()), jamonWriter);
    // 341, 48
    jamonWriter.write(" </td>\r\n                    <td>Addresses of all registered ZK servers. For more, see <a href=\"/zk.jsp\">zk dump</a>.</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>ZooKeeper Base Path</td>\r\n                    <td> ");
    // 346, 26
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(master.getZooKeeper().getZNodePaths().baseZNode), jamonWriter);
    // 346, 79
    jamonWriter.write("</td>\r\n                    <td>Root node of this cluster in ZK.</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>Cluster Key</td>\r\n                    <td> ");
    // 351, 26
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(formatZKString()), jamonWriter);
    // 351, 48
    jamonWriter.write(":");
    // 351, 49
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(master.getZooKeeper().getZNodePaths().baseZNode), jamonWriter);
    // 351, 102
    jamonWriter.write("</td>\r\n                    <td>Key to add this cluster as a peer for replication. Use 'help \"add_peer\"' in the shell for details.</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>HBase Root Directory</td>\r\n                    <td>");
    // 356, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(FSUtils.getRootDir(master.getConfiguration()).toString()), jamonWriter);
    // 356, 87
    jamonWriter.write("</td>\r\n                    <td>Location of HBase home directory</td>\r\n                </tr>\r\n                <tr>\r\n                    <td>HMaster Start Time</td>\r\n                    <td>");
    // 361, 25
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(new Date(master.getMasterStartTime())), jamonWriter);
    // 361, 68
    jamonWriter.write("</td>\r\n                    <td>Date stamp of when this HMaster was started</td>\r\n                </tr>\r\n                ");
    // 364, 17
    if (master.isActiveMaster() )
    {
      // 364, 48
      jamonWriter.write("\r\n\t                <tr>\r\n\t                    <td>HMaster Active Time</td>\r\n\t                    <td>");
      // 367, 26
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(new Date(master.getMasterActiveTime())), jamonWriter);
      // 367, 70
      jamonWriter.write("</td>\r\n\t                    <td>Date stamp of when this HMaster became active</td>\r\n\t                </tr>\r\n\t                <tr>\r\n\t                    <td>HBase Cluster ID</td>\r\n\t                    <td>");
      // 372, 26
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(master.getClusterId() != null ? master.getClusterId() : "Not set"), jamonWriter);
      // 372, 97
      jamonWriter.write("</td>\r\n\t                    <td>Unique identifier generated for each HBase cluster</td>\r\n\t                </tr>\r\n\t                <tr>\r\n\t                    <td>Load average</td>\r\n\t                    <td>");
      // 377, 26
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(master.getServerManager() == null ? "0.00" :
	                      StringUtils.limitDecimalTo2(master.getServerManager().getAverageLoad())), jamonWriter);
      // 378, 98
      jamonWriter.write("</td>\r\n\t                    <td>Average number of regions per regionserver. Naive computation.</td>\r\n\t                </tr>\r\n\t                ");
      // 381, 18
      if (frags != null )
      {
        // 381, 39
        jamonWriter.write("\r\n\t                <tr>\r\n\t                    <td>Fragmentation</td>\r\n\t                    <td>");
        // 384, 26
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(frags.get("-TOTAL-") != null ? frags.get("-TOTAL-").intValue() + "%" : "n/a"), jamonWriter);
        // 384, 108
        jamonWriter.write("</td>\r\n\t                    <td>Overall fragmentation of all tables, including hbase:meta</td>\r\n\t                </tr>\r\n\t                ");
      }
      // 387, 24
      jamonWriter.write("\r\n\t                <tr>\r\n\t                    <td>Coprocessors</td>\r\n\t                    <td>");
      // 390, 26
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(master.getMasterCoprocessorHost() == null ? "[]" :
	                      java.util.Arrays.toString(master.getMasterCoprocessors())), jamonWriter);
      // 391, 84
      jamonWriter.write("</td>\r\n\t                    <td>Coprocessors currently loaded by the master</td>\r\n\t                </tr>\r\n\t                <tr>\r\n\t                    <td>LoadBalancer</td>\r\n\t                    <td>");
      // 396, 26
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(master.getLoadBalancerClassName()), jamonWriter);
      // 396, 65
      jamonWriter.write("</td>\r\n\t                    <td>LoadBalancer to be used in the Master</td>\r\n\t                </tr>\r\n                ");
    }
    // 399, 23
    jamonWriter.write("\r\n            </table>\r\n        </section>\r\n        </div>\r\n    </div> <!-- /container -->\r\n\r\n    <script src=\"/static/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n    <script src=\"/static/js/jquery.tablesorter.min.js\" type=\"text/javascript\"></script>\r\n    <script src=\"/static/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n    <script src=\"/static/js/tab.js\" type=\"text/javascript\"></script>\r\n    <script>\r\n    $(document).ready(function()\r\n        {\r\n            $(\"#baseStatsTable\").tablesorter();\r\n            $(\"#memoryStatsTable\").tablesorter();\r\n            $(\"#requestStatsTable\").tablesorter();\r\n            $(\"#storeStatsTable\").tablesorter();\r\n            $(\"#compactionStatsTable\").tablesorter();\r\n\r\n            $(\"#userTables\").tablesorter();\r\n        }\r\n    );\r\n    </script>\r\n  </body>\r\n</html>\r\n\r\n");
  }
  
  
  // 425, 1
  private void __jamon_innerUnit__catalogTables(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 426, 1
    
 List<TableDescriptor> sysTables = master.isInitialized() ?
   master.listTableDescriptorsByNamespace(NamespaceDescriptor.SYSTEM_NAMESPACE_NAME_STR) : null;

    // 430, 1
    if ((sysTables != null && sysTables.size() > 0))
    {
      // 430, 51
      jamonWriter.write("\r\n<table class=\"table table-striped\">\r\n<tr>\r\n    <th>Table Name</th>\r\n    ");
      // 434, 5
      if ((frags != null) )
      {
        // 434, 28
        jamonWriter.write("\r\n        <th title=\"Fragmentation - Will be 0% after a major compaction and fluctuate during normal usage.\">Frag.</th>\r\n    ");
      }
      // 436, 11
      jamonWriter.write("\r\n    <th>Description</th>\r\n</tr>\r\n");
      // 439, 1
      for (TableDescriptor systemTable : sysTables)
      {
        // 439, 48
        jamonWriter.write("\r\n<tr>\r\n");
        // 441, 1
        TableName tableName = systemTable.getTableName();
        // 442, 5
        jamonWriter.write("<td><a href=\"table.jsp?name=");
        // 442, 33
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tableName), jamonWriter);
        // 442, 48
        jamonWriter.write("\">");
        // 442, 50
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tableName), jamonWriter);
        // 442, 65
        jamonWriter.write("</a></td>\r\n    ");
        // 443, 5
        if ((frags != null))
        {
          // 443, 27
          jamonWriter.write("\r\n        <td align=\"center\">");
          // 444, 28
          org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(frags.get(tableName.getNameAsString()) != null ? frags.get(tableName.getNameAsString())
        .intValue() + "%" : "n/a"), jamonWriter);
          // 445, 37
          jamonWriter.write("</td>\r\n    ");
        }
        // 446, 11
        jamonWriter.write("\r\n    ");
        // 447, 5
        String description = null;
        if (tableName.equals(TableName.META_TABLE_NAME)){
            description = "The hbase:meta table holds references to all User Table regions.";
        } else if (tableName.equals(CanaryTool.DEFAULT_WRITE_TABLE_NAME)){
            description = "The hbase:canary table is used to sniff the write availbility of"
              + " each regionserver.";
        } else if (tableName.equals(AccessControlLists.ACL_TABLE_NAME)){
            description = "The hbase:acl table holds information about acl.";
        } else if (tableName.equals(VisibilityConstants.LABELS_TABLE_NAME)){
            description = "The hbase:labels table holds information about visibility labels.";
        } else if (tableName.equals(TableName.NAMESPACE_TABLE_NAME)){
            description = "The hbase:namespace table holds information about namespaces.";
        } else if (tableName.equals(QuotaUtil.QUOTA_TABLE_NAME)){
            description = "The hbase:quota table holds quota information about number" +
            " or size of requests in a given time frame.";
        } else if (tableName.equals(TableName.valueOf("hbase:rsgroup"))){
            description = "The hbase:rsgroup table holds information about regionserver groups.";
        } else if (tableName.equals(TableName.valueOf("hbase:replication"))) {
            description = "The hbase:replication table tracks cross cluster replication through " +
            "WAL file offsets.";
        }
    
        // 469, 5
        jamonWriter.write("<td>");
        // 469, 9
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(description), jamonWriter);
        // 469, 26
        jamonWriter.write("</td>\r\n</tr>\r\n");
      }
      // 471, 8
      jamonWriter.write("\r\n</table>\r\n");
    }
    // 473, 7
    jamonWriter.write("\r\n");
  }
  
  
  // 589, 1
  private void __jamon_innerUnit__deadRegionServers(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 591, 1
    if ((deadServers != null && deadServers.size() > 0))
    {
      // 591, 55
      jamonWriter.write("\r\n<h2>Dead Region Servers</h2>\r\n<table class=\"table table-striped\">\r\n    <tr>\r\n        <th></th>\r\n        <th>ServerName</th>\r\n        <th>Stop time</th>\r\n    </tr>\r\n    ");
      // 599, 5
      
       DeadServer deadServerUtil = master.getServerManager().getDeadServers();
       ServerName [] deadServerNames = deadServers.toArray(new ServerName[deadServers.size()]);
         Arrays.sort(deadServerNames);
         for (ServerName deadServerName: deadServerNames) {
    
      // 605, 5
      jamonWriter.write("<tr>\r\n    \t<th></th>\r\n        <td>");
      // 607, 13
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(deadServerName), jamonWriter);
      // 607, 33
      jamonWriter.write("</td>\r\n        <td>");
      // 608, 13
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(deadServerUtil.getTimeOfDeath(deadServerName)), jamonWriter);
      // 608, 64
      jamonWriter.write("</td>\r\n    </tr>\r\n    ");
      // 610, 5
      
        }
    
      // 613, 5
      jamonWriter.write("<tr>\r\n        <th>Total: </th>\r\n        <td>servers: ");
      // 615, 22
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(deadServers.size()), jamonWriter);
      // 615, 46
      jamonWriter.write("</td>\r\n        <th></th>\r\n    </tr>\r\n</table>\r\n");
    }
    // 619, 7
    jamonWriter.write("\r\n");
  }
  
  
  // 622, 1
  private void __jamon_innerUnit__peerConfigs(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 623, 1
    
    List<ReplicationPeerDescription> peers = null;
    if (master.getReplicationPeerManager() != null) {
        peers = master.getReplicationPeerManager().listPeers(null);
    }

    // 629, 1
    jamonWriter.write("<table class=\"table table-striped\">\r\n    <tr>\r\n        <th>Peer Id</th>\r\n        <th>Cluster Key</th>\r\n        <th>Endpoint</th>\r\n        <th>State</th>\r\n        <th>IsSerial</th>\r\n        <th>Bandwidth</th>\r\n        <th>ReplicateAll</th>\r\n        <th>Namespaces</th>\r\n        <th>Exclude Namespaces</th>\r\n        <th>Table Cfs</th>\r\n        <th>Exclude Table Cfs</th>\r\n    </tr>\r\n");
    // 643, 1
    if ((peers != null && peers.size() > 0))
    {
      // 643, 43
      jamonWriter.write("\r\n    ");
      // 644, 5
      for (ReplicationPeerDescription peer : peers )
      {
        // 644, 53
        jamonWriter.write("\r\n    ");
        // 645, 5
        
        String peerId = peer.getPeerId();
        ReplicationPeerConfig peerConfig = peer.getPeerConfig();
    
        // 649, 5
        jamonWriter.write("<tr>\r\n        <td>");
        // 650, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerId), jamonWriter);
        // 650, 25
        jamonWriter.write("</td>\r\n        <td>");
        // 651, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.getClusterKey()), jamonWriter);
        // 651, 45
        jamonWriter.write("</td>\r\n        <td>");
        // 652, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.getReplicationEndpointImpl()), jamonWriter);
        // 652, 58
        jamonWriter.write("</td>\r\n        <td>");
        // 653, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peer.isEnabled() ? "ENABLED" : "DISABLED"), jamonWriter);
        // 653, 60
        jamonWriter.write("</td>\r\n        <td>");
        // 654, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.isSerial()), jamonWriter);
        // 654, 40
        jamonWriter.write("</td>\r\n        <td>");
        // 655, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.getBandwidth() == 0? "UNLIMITED" : StringUtils.humanReadableInt(peerConfig.getBandwidth())), jamonWriter);
        // 655, 120
        jamonWriter.write("</td>\r\n        <td>");
        // 656, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.replicateAllUserTables()), jamonWriter);
        // 656, 54
        jamonWriter.write("</td>\r\n        <td>\r\n           ");
        // 658, 12
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.getNamespaces() == null ? "" : ReplicationPeerConfigUtil.convertToString(peerConfig.getNamespaces()).replaceAll(";", "; ")), jamonWriter);
        // 658, 151
        jamonWriter.write("\r\n        </td>\r\n        <td>\r\n            ");
        // 661, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.getExcludeNamespaces() == null ? "" : ReplicationPeerConfigUtil.convertToString(peerConfig.getExcludeNamespaces()).replaceAll(";", "; ")), jamonWriter);
        // 661, 166
        jamonWriter.write("\r\n        </td>\r\n        <td>\r\n           ");
        // 664, 12
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.getTableCFsMap() == null ? "" : ReplicationPeerConfigUtil.convertToString(peerConfig.getTableCFsMap()).replaceAll(";", "; ")), jamonWriter);
        // 664, 153
        jamonWriter.write("\r\n        </td>\r\n        <td>\r\n           ");
        // 667, 12
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(peerConfig.getExcludeTableCFsMap() == null ? "" : ReplicationPeerConfigUtil.convertToString(peerConfig.getExcludeTableCFsMap()).replaceAll(";", "; ")), jamonWriter);
        // 667, 167
        jamonWriter.write("\r\n        </td>\r\n    </tr>\r\n    ");
      }
      // 670, 12
      jamonWriter.write("\r\n");
    }
    // 671, 7
    jamonWriter.write("\r\n<tr><td>Total: ");
    // 672, 16
    org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf((peers != null) ? peers.size() : 0), jamonWriter);
    // 672, 56
    jamonWriter.write("</td></tr>\r\n</table>\r\n");
  }
  
  
  // 560, 1
  private void __jamon_innerUnit__userSnapshots(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 561, 1
    
   List<SnapshotDescription> snapshots = master.isInitialized() ?
     master.getSnapshotManager().getCompletedSnapshots() : null;

    // 565, 1
    if ((snapshots != null && snapshots.size() > 0))
    {
      // 565, 51
      jamonWriter.write("\r\n<table class=\"table table-striped\">\r\n    <tr>\r\n        <th>Snapshot Name</th>\r\n        <th>Table</th>\r\n        <th>Creation Time</th>\r\n    </tr>\r\n    ");
      // 572, 5
      for (SnapshotDescription snapshotDesc : snapshots)
      {
        // 572, 57
        jamonWriter.write("\r\n    ");
        // 573, 5
        
        TableName snapshotTable = TableName.valueOf(snapshotDesc.getTable());
    
        // 576, 5
        jamonWriter.write("<tr>\r\n        <td><a href=\"snapshot.jsp?name=");
        // 577, 40
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(snapshotDesc.getName()), jamonWriter);
        // 577, 68
        jamonWriter.write("\">");
        // 577, 70
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(snapshotDesc.getName()), jamonWriter);
        // 577, 98
        jamonWriter.write("</a> </td>\r\n        <td><a href=\"table.jsp?name=");
        // 578, 37
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(snapshotTable.getNameAsString()), jamonWriter);
        // 578, 74
        jamonWriter.write("\">");
        // 578, 76
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(snapshotTable.getNameAsString()), jamonWriter);
        // 578, 113
        jamonWriter.write("</a>\r\n        </td>\r\n        <td>");
        // 580, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(new Date(snapshotDesc.getCreationTime())), jamonWriter);
        // 580, 59
        jamonWriter.write("</td>\r\n    </tr>\r\n    ");
      }
      // 582, 12
      jamonWriter.write("\r\n    <p>");
      // 583, 8
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(snapshots.size()), jamonWriter);
      // 583, 30
      jamonWriter.write(" snapshot(s) in set. [<a href=\"/snapshotsStats.jsp\">Snapshot Storefile stats</a>]</p>\r\n</table>\r\n");
    }
    // 585, 7
    jamonWriter.write("\r\n");
  }
  
  
  // 476, 1
  private void __jamon_innerUnit__userTables(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 477, 1
    
   List<TableDescriptor> tables = new ArrayList<TableDescriptor>();
   String errorMessage = getUserTables(master, tables);

    // 481, 1
    if ((tables.size() == 0 && errorMessage != null))
    {
      // 481, 52
      jamonWriter.write("\r\n<p> ");
      // 482, 5
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(errorMessage), jamonWriter);
      // 482, 23
      jamonWriter.write(" </p>\r\n");
    }
    // 483, 7
    jamonWriter.write("\r\n\r\n");
    // 485, 1
    if ((tables != null && tables.size() > 0))
    {
      // 485, 45
      jamonWriter.write("\r\n<table id=\"userTables\" class=\"tablesorter table table-striped\">\r\n<thead>\r\n    <tr>\r\n        <th style=\"vertical-align: middle;\" rowspan=\"2\">Namespace</th>\r\n        <th style=\"vertical-align: middle;\" rowspan=\"2\">Name</th>\r\n        ");
      // 491, 9
      if ((frags != null) )
      {
        // 491, 32
        jamonWriter.write("\r\n            <th title=\"Fragmentation - Will be 0% after a major compaction and fluctuate during normal usage.\">Frag.</th>\r\n        ");
      }
      // 493, 15
      jamonWriter.write("\r\n        <th style=\"vertical-align:middle;\" rowspan=\"2\">State</th>\r\n        <th style=\"text-align: center\" colspan=\"8\">Regions</th>\r\n        <th style=\"vertical-align:middle;\" rowspan=\"2\">Description</th>\r\n    </tr>\r\n    <tr>\r\n        <th>OPEN</th>\r\n        <th>OPENING</th>\r\n        <th>CLOSED</th>\r\n        <th>CLOSING</th>\r\n        <th>OFFLINE</th>\r\n        <th>FAILED</th>\r\n        <th>SPLIT</th>\r\n        <th>Other</th>\r\n    </tr>\r\n</thead>\r\n<tbody>\r\n    ");
      // 510, 5
      for (TableDescriptor desc : tables)
      {
        // 510, 42
        jamonWriter.write("\r\n    ");
        // 511, 5
        
      HTableDescriptor htDesc = new HTableDescriptor(desc);
      TableName tableName = htDesc.getTableName();
      TableState tableState = master.getTableStateManager().getTableState(tableName);
      Map<RegionState.State, List<RegionInfo>> tableRegions =
          master.getAssignmentManager().getRegionStates()
            .getRegionByStateOfTable(tableName);
      int openRegionsCount = tableRegions.get(RegionState.State.OPEN).size();
      int openingRegionsCount = tableRegions.get(RegionState.State.OPENING).size();
      int closedRegionsCount = tableRegions.get(RegionState.State.CLOSED).size();
      int closingRegionsCount = tableRegions.get(RegionState.State.CLOSING).size();
      int offlineRegionsCount = tableRegions.get(RegionState.State.OFFLINE).size();
      int splitRegionsCount = tableRegions.get(RegionState.State.SPLIT).size();
      int failedRegionsCount = tableRegions.get(RegionState.State.FAILED_OPEN).size()
             + tableRegions.get(RegionState.State.FAILED_CLOSE).size();
      int otherRegionsCount = 0;
      for (List<RegionInfo> list: tableRegions.values()) {
         otherRegionsCount += list.size();
      }
      // now subtract known states
      otherRegionsCount = otherRegionsCount - openRegionsCount
                     - failedRegionsCount - offlineRegionsCount
                     - splitRegionsCount - openingRegionsCount
                     - closedRegionsCount - closingRegionsCount;
    
        // 536, 5
        jamonWriter.write("<tr>\r\n        <td>");
        // 537, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tableName.getNamespaceAsString()), jamonWriter);
        // 537, 51
        jamonWriter.write("</td>\r\n        <td><a href=table.jsp?name=");
        // 538, 36
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tableName.getNameAsString()), jamonWriter);
        // 538, 69
        jamonWriter.write(">");
        // 538, 70
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tableName.getQualifierAsString()), jamonWriter);
        // 538, 108
        jamonWriter.write("</a> </td>\r\n        ");
        // 539, 9
        if ((frags != null) )
        {
          // 539, 32
          jamonWriter.write("\r\n            <td align=\"center\">");
          // 540, 32
          org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(frags.get(tableName.getNameAsString()) != null ? frags.get(tableName.getNameAsString()).intValue() + "%" : "n/a"), jamonWriter);
          // 540, 150
          jamonWriter.write("</td>\r\n        ");
        }
        // 541, 15
        jamonWriter.write("\r\n        <td>");
        // 542, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tableState.getState()), jamonWriter);
        // 542, 40
        jamonWriter.write("</td>\r\n        <td>");
        // 543, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(openRegionsCount), jamonWriter);
        // 543, 35
        jamonWriter.write("</td>\r\n        ");
        // 544, 9
        if ((openingRegionsCount > 0) )
        {
          // 544, 42
          jamonWriter.write(" <td><a href=\"/rits.jsp?table=");
          // 544, 72
          org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tableName.getNameAsString()), jamonWriter);
          // 544, 105
          jamonWriter.write("&state=OPENING\">");
          // 544, 121
          org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(openingRegionsCount), jamonWriter);
          // 544, 146
          jamonWriter.write("</td> ");
        }
        // 544, 152
        else
        {
          // 544, 159
          jamonWriter.write("<td>");
          // 544, 163
          org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(openingRegionsCount), jamonWriter);
          // 544, 188
          jamonWriter.write("</td> ");
        }
        // 544, 200
        jamonWriter.write("\r\n        <td>");
        // 545, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(closedRegionsCount), jamonWriter);
        // 545, 37
        jamonWriter.write("</td>\r\n        ");
        // 546, 9
        if ((closingRegionsCount > 0) )
        {
          // 546, 42
          jamonWriter.write(" <td><a href=\"/rits.jsp?table=");
          // 546, 72
          org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tableName.getNameAsString()), jamonWriter);
          // 546, 105
          jamonWriter.write("&state=CLOSING\">");
          // 546, 121
          org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(closingRegionsCount), jamonWriter);
          // 546, 146
          jamonWriter.write("</td> ");
        }
        // 546, 152
        else
        {
          // 546, 159
          jamonWriter.write("<td>");
          // 546, 163
          org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(closingRegionsCount), jamonWriter);
          // 546, 188
          jamonWriter.write("</td> ");
        }
        // 546, 200
        jamonWriter.write("\r\n        <td>");
        // 547, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(offlineRegionsCount), jamonWriter);
        // 547, 38
        jamonWriter.write("</td>\r\n        <td>");
        // 548, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(failedRegionsCount), jamonWriter);
        // 548, 37
        jamonWriter.write("</td>\r\n        <td>");
        // 549, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(splitRegionsCount), jamonWriter);
        // 549, 36
        jamonWriter.write("</td>\r\n        <td>");
        // 550, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(otherRegionsCount), jamonWriter);
        // 550, 36
        jamonWriter.write("</td>\r\n        <td>");
        // 551, 13
        org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(htDesc.toStringCustomizedValues()), jamonWriter);
        // 551, 52
        jamonWriter.write("</td>\r\n    </tr>\r\n    ");
      }
      // 553, 12
      jamonWriter.write("\r\n    <p>");
      // 554, 8
      org.jamon.escaping.Escaping.NONE.write(org.jamon.emit.StandardEmitter.valueOf(tables.size()), jamonWriter);
      // 554, 27
      jamonWriter.write(" table(s) in set. [<a href=tablesDetailed.jsp>Details</a>]</p>\r\n</tbody>\r\n</table>\r\n");
    }
    // 557, 7
    jamonWriter.write("\r\n");
  }
  
  
}
