// Autogenerated Jamon implementation
// /root/apps/test/jamon-dist-2013.12.28/./jamon/org/apache/hadoop/hbase/tmpl/regionserver/ServerMetricsTmpl.jamon

package org.apache.hadoop.hbase.tmpl.regionserver;

// 24, 1
import java.util.*;
// 25, 1
import org.apache.hadoop.hbase.regionserver.HRegionServer;
// 26, 1
import org.apache.hadoop.hbase.ipc.MetricsHBaseServerWrapper;
// 27, 1
import org.apache.hadoop.hbase.regionserver.MetricsRegionServerWrapper;
// 28, 1
import org.apache.hadoop.hbase.util.Bytes;
// 29, 1
import org.apache.hadoop.hbase.HRegionInfo;
// 30, 1
import org.apache.hadoop.hbase.ServerName;
// 31, 1
import org.apache.hadoop.hbase.HBaseConfiguration;
// 32, 1
import org.apache.hadoop.hbase.protobuf.ProtobufUtil;
// 33, 1
import org.apache.hadoop.hbase.protobuf.generated.AdminProtos.ServerInfo;
// 34, 1
import org.apache.hadoop.hbase.protobuf.generated.ClusterStatusProtos.RegionLoad;
// 35, 1
import org.apache.hadoop.hbase.util.DirectMemoryUtils;
// 36, 1
import org.apache.hadoop.util.StringUtils.TraditionalBinaryPrefix;
// 37, 1
import java.lang.management.MemoryUsage;
// 38, 1
import org.apache.hadoop.hbase.io.util.MemorySizeUtil;

public class ServerMetricsTmplImpl
  extends org.jamon.AbstractTemplateImpl
  implements org.apache.hadoop.hbase.tmpl.regionserver.ServerMetricsTmpl.Intf

{
  private final MetricsRegionServerWrapper mWrap;
  private final MetricsHBaseServerWrapper mServerWrap;
  protected static org.apache.hadoop.hbase.tmpl.regionserver.ServerMetricsTmpl.ImplData __jamon_setOptionalArguments(org.apache.hadoop.hbase.tmpl.regionserver.ServerMetricsTmpl.ImplData p_implData)
  {
    return p_implData;
  }
  public ServerMetricsTmplImpl(org.jamon.TemplateManager p_templateManager, org.apache.hadoop.hbase.tmpl.regionserver.ServerMetricsTmpl.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    mWrap = p_implData.getMWrap();
    mServerWrap = p_implData.getMServerWrap();
  }
  
  @Override public void renderNoFlush(final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 40, 1
    jamonWriter.write("<div class=\"tabbable\">\r\n    <ul class=\"nav nav-pills\">\r\n        <li class=\"active\"><a href=\"#tab_baseStats\" data-toggle=\"tab\">Base Stats</a></li>\r\n        <li class=\"\"><a href=\"#tab_memoryStats\" data-toggle=\"tab\">Memory</a></li>\r\n        <li class=\"\"><a href=\"#tab_requestStats\" data-toggle=\"tab\">Requests</a></li>\r\n        <li class=\"\"><a href=\"#tab_walStats\" data-toggle=\"tab\">WALs</a></li>\r\n        <li class=\"\"><a href=\"#tab_storeStats\" data-toggle=\"tab\">Storefiles</a></li>\r\n        <li class=\"\"><a href=\"#tab_queueStats\" data-toggle=\"tab\">Queues</a></li>\r\n    </ul>\r\n    <div class=\"tab-content\" style=\"padding-bottom: 9px; border-bottom: 1px solid #ddd;\">\r\n        <div class=\"tab-pane active\" id=\"tab_baseStats\">\r\n            ");
    // 51, 13
    {
      // 51, 13
      __jamon_innerUnit__baseStats(jamonWriter, mWrap );
    }
    // 51, 43
    jamonWriter.write("\r\n        </div>\r\n        <div class=\"tab-pane\" id=\"tab_memoryStats\">\r\n            ");
    // 54, 13
    {
      // 54, 13
      __jamon_innerUnit__memoryStats(jamonWriter, mWrap );
    }
    // 54, 45
    jamonWriter.write("\r\n        </div>\r\n        <div class=\"tab-pane\" id=\"tab_requestStats\">\r\n            ");
    // 57, 13
    {
      // 57, 13
      __jamon_innerUnit__requestStats(jamonWriter, mWrap );
    }
    // 57, 46
    jamonWriter.write("\r\n        </div>\r\n        <div class=\"tab-pane\" id=\"tab_walStats\">\r\n            ");
    // 60, 13
    {
      // 60, 13
      __jamon_innerUnit__walStats(jamonWriter, mWrap );
    }
    // 60, 42
    jamonWriter.write("\r\n        </div>\r\n        <div class=\"tab-pane\" id=\"tab_storeStats\">\r\n            ");
    // 63, 13
    {
      // 63, 13
      __jamon_innerUnit__storeStats(jamonWriter, mWrap );
    }
    // 63, 44
    jamonWriter.write("\r\n        </div>\r\n        <div class=\"tab-pane\" id=\"tab_queueStats\">\r\n            ");
    // 66, 13
    {
      // 66, 13
      __jamon_innerUnit__queueStats(jamonWriter, mWrap, mServerWrap);
    }
    // 66, 72
    jamonWriter.write("\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");
  }
  
  
  // 71, 1
  private void __jamon_innerUnit__baseStats(final java.io.Writer jamonWriter, final MetricsRegionServerWrapper mWrap)
    throws java.io.IOException
  {
    // 75, 1
    jamonWriter.write("<table class=\"table table-striped\">\r\n    <tr>\r\n\r\n        <th>Requests Per Second</th>\r\n        <th>Num. Regions</th>\r\n        <th>Block locality</th>\r\n        <th>Block locality (Secondary replicas)</th>\r\n        <th>Slow WAL Append Count</th>\r\n    </tr>\r\n    <tr>\r\n        <td>");
    // 85, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%.0f", mWrap.getRequestsPerSecond())), jamonWriter);
    // 85, 70
    jamonWriter.write("</td>\r\n        <td>");
    // 86, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getNumOnlineRegions()), jamonWriter);
    // 86, 46
    jamonWriter.write("</td>\r\n        <td>");
    // 87, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getPercentFileLocal()), jamonWriter);
    // 87, 46
    jamonWriter.write("</td>\r\n        <td>");
    // 88, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getPercentFileLocalSecondaryRegions()), jamonWriter);
    // 88, 62
    jamonWriter.write("</td>\r\n        <td>");
    // 89, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getNumWALSlowAppend()), jamonWriter);
    // 89, 46
    jamonWriter.write("</td>\r\n    </tr>\r\n</table>\r\n");
  }
  
  
  // 94, 1
  private void __jamon_innerUnit__memoryStats(final java.io.Writer jamonWriter, final MetricsRegionServerWrapper mWrap)
    throws java.io.IOException
  {
    // 98, 1
    long usedHeap = -1L;
  long maxHeap = -1L;
  final MemoryUsage usage = MemorySizeUtil.safeGetHeapMemoryUsage();
  if (usage != null) {
    maxHeap = usage.getMax();
    usedHeap = usage.getUsed();
  }

    // 107, 1
    jamonWriter.write("<table class=\"table table-striped\">\r\n<tr>\r\n    <tr>\r\n        <th>Used Heap</th>\r\n        <th>Max Heap</th>\r\n        <th>Direct Memory Used</th>\r\n        <th>Direct Memory Configured</th>\r\n        <th>Memstore Size</th>\r\n        <th>Memstore Limit</th>\r\n    </tr>\r\n</tr>\r\n<tr>\r\n    <td>\r\n        ");
    // 120, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(usedHeap, "B", 1)), jamonWriter);
    // 120, 68
    jamonWriter.write("\r\n    </td>\r\n    <td>\r\n        ");
    // 123, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(maxHeap, "B", 1)), jamonWriter);
    // 123, 67
    jamonWriter.write("\r\n    </td>\r\n    <td>\r\n        ");
    // 126, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(DirectMemoryUtils.getDirectMemoryUsage(), "B", 1)), jamonWriter);
    // 126, 100
    jamonWriter.write("\r\n    </td>\r\n    <td>\r\n        ");
    // 129, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(DirectMemoryUtils.getDirectMemorySize(), "B", 1)), jamonWriter);
    // 129, 99
    jamonWriter.write("\r\n    </td>\r\n    <td>\r\n        ");
    // 132, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(mWrap.getMemStoreSize(), "B", 1)), jamonWriter);
    // 132, 83
    jamonWriter.write("\r\n    </td>\r\n    <td>\r\n        ");
    // 135, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(mWrap.getMemStoreLimit(), "B", 1)), jamonWriter);
    // 135, 84
    jamonWriter.write("\r\n    </td>\r\n</tr>\r\n</table>\r\n");
  }
  
  
  // 203, 1
  private void __jamon_innerUnit__queueStats(final java.io.Writer jamonWriter, final MetricsRegionServerWrapper mWrap, final MetricsHBaseServerWrapper mServerWrap)
    throws java.io.IOException
  {
    // 208, 1
    jamonWriter.write("<table class=\"table table-striped\">\r\n<tr>\r\n    <th>Compaction Queue Length</th>\r\n    <th>Flush Queue Length</th>\r\n    <th>Priority Call Queue Length</th>\r\n    <th>General Call Queue Length</th>\r\n    <th>Replication Call Queue Length</th>\r\n    <th>Total Call Queue Size</th>\r\n\r\n</tr>\r\n<tr>\r\n    <td>");
    // 219, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getCompactionQueueSize()), jamonWriter);
    // 219, 45
    jamonWriter.write("</td>\r\n    <td>");
    // 220, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getFlushQueueSize()), jamonWriter);
    // 220, 40
    jamonWriter.write("</td>\r\n    <td>");
    // 221, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mServerWrap.getPriorityQueueLength()), jamonWriter);
    // 221, 51
    jamonWriter.write("</td>\r\n    <td>");
    // 222, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mServerWrap.getGeneralQueueLength()), jamonWriter);
    // 222, 50
    jamonWriter.write("</td>\r\n    <td>");
    // 223, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mServerWrap.getReplicationQueueLength()), jamonWriter);
    // 223, 54
    jamonWriter.write("</td>\r\n    <td>");
    // 224, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(mServerWrap.getTotalQueueSize(), "B", 1)), jamonWriter);
    // 224, 91
    jamonWriter.write("</td>\r\n</tr>\r\n</table>\r\n");
  }
  
  
  // 183, 1
  private void __jamon_innerUnit__requestStats(final java.io.Writer jamonWriter, final MetricsRegionServerWrapper mWrap)
    throws java.io.IOException
  {
    // 187, 1
    jamonWriter.write("<table class=\"table table-striped\">\r\n<tr>\r\n    <th>Request Per Second</th>\r\n    <th>Read Request Count</th>\r\n    <th>Filtered Read Request Count</th>\r\n    <th>Write Request Count</th>\r\n</tr>\r\n<tr>\r\n    <td>");
    // 195, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(String.format("%.0f", mWrap.getRequestsPerSecond())), jamonWriter);
    // 195, 66
    jamonWriter.write("</td>\r\n    <td>");
    // 196, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getReadRequestsCount()), jamonWriter);
    // 196, 43
    jamonWriter.write("</td>\r\n    <td>");
    // 197, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getFilteredReadRequestsCount()), jamonWriter);
    // 197, 51
    jamonWriter.write("</td>\r\n    <td>");
    // 198, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getWriteRequestsCount()), jamonWriter);
    // 198, 44
    jamonWriter.write("</td>\r\n</tr>\r\n</table>\r\n");
  }
  
  
  // 159, 1
  private void __jamon_innerUnit__storeStats(final java.io.Writer jamonWriter, final MetricsRegionServerWrapper mWrap)
    throws java.io.IOException
  {
    // 163, 1
    jamonWriter.write("<table class=\"table table-striped\">\r\n<tr>\r\n\r\n    <th>Num. Stores</th>\r\n    <th>Num. Storefiles</th>\r\n    <th>Root Index Size</th>\r\n    <th>Index Size</th>\r\n    <th>Bloom Size</th>\r\n</tr>\r\n<tr>\r\n    <td>");
    // 173, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getNumStores()), jamonWriter);
    // 173, 35
    jamonWriter.write("</td>\r\n    <td>");
    // 174, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getNumStoreFiles()), jamonWriter);
    // 174, 39
    jamonWriter.write("</td>\r\n    <td>");
    // 175, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(mWrap.getStoreFileIndexSize(), "B", 1)), jamonWriter);
    // 175, 89
    jamonWriter.write("</td>\r\n    <td>");
    // 176, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(mWrap.getTotalStaticIndexSize(), "B", 1)), jamonWriter);
    // 176, 91
    jamonWriter.write("</td>\r\n    <td>");
    // 177, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(mWrap.getTotalStaticBloomSize(), "B", 1)), jamonWriter);
    // 177, 91
    jamonWriter.write("</td>\r\n</tr>\r\n</table>\r\n");
  }
  
  
  // 141, 1
  private void __jamon_innerUnit__walStats(final java.io.Writer jamonWriter, final MetricsRegionServerWrapper mWrap)
    throws java.io.IOException
  {
    // 145, 1
    jamonWriter.write("<table class=\"table table-striped\">\r\n<tr>\r\n    <tr>\r\n        <th>Num. WAL Files</th>\r\n        <th>Size. WAL Files</th>\r\n    </tr>\r\n</tr>\r\n<tr>\r\n    <td>");
    // 153, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(mWrap.getNumWALFiles()), jamonWriter);
    // 153, 37
    jamonWriter.write("</td>\r\n    <td>");
    // 154, 9
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(TraditionalBinaryPrefix.long2String(mWrap.getWALFileSize(), "B", 1)), jamonWriter);
    // 154, 82
    jamonWriter.write("</td>\r\n</tr>\r\n</table>\r\n");
  }
  
  
}
