/*
 * Generated by src/saveVersion.sh
 */
package org.apache.hadoop.hbase;

import org.apache.yetus.audience.InterfaceAudience;

@InterfaceAudience.Private
public class Version {
    public static final String version = "2.1.4";
    public static final String revision = "5b7722f8551bca783adb36a920ca77e417ca99d1";
    public static final String user = "hbase-rm";
    public static final String date = "Wed Mar 20 06:44:36 UTC 2019";
    public static final String url = "git://c647044a8f90/opt/hbase-rm/output/hbase";
    public static final String srcChecksum = "d210900ccde556a0bd80acd860998807";
}
